blueprint:
  name: Android sticky notification for entity state (auto-dismiss)
  description: >
    Sends a persistent (sticky) notification to an Android phone when an entity
    enters a target state, and clears it when the entity leaves that state.
    Requires Home Assistant Companion App on Android.
  domain: automation

  input:
    target_entity:
      name: Entity to monitor
      selector:
        entity: {}

    target_state:
      name: State that triggers the sticky notification
      description: 'Example: on, open, home, playing, locked'
      default: "on"
      selector:
        text: {}

    notify_service:
      name: Android notify service
      description: Select notify.mobile_app_<your_phone>
      selector:
        service:
          domain: notify

    title:
      name: Notification title
      default: "Home Assistant"
      selector:
        text: {}

    message:
      name: Notification message (optional)
      description: Leave blank to auto-generate.
      default: ""
      selector:
        text:
          multiline: true

    notification_tag:
      name: Notification tag (used to update/clear)
      description: Must be unique per automation/phone (e.g. sticky_light_kitchen)
      default: "ha_sticky_state"
      selector:
        text: {}

    channel:
      name: Android notification channel (optional)
      default: ""
      selector:
        text: {}

    importance:
      name: Android importance (optional)
      default: "default"
      selector:
        select:
          options:
            - min
            - low
            - default
            - high
            - max

    make_sticky:
      name: Make notification sticky (persistent)
      default: true
      selector:
        boolean: {}

    show_when_unavailable:
      name: Also notify when entity is unavailable/unknown
      default: false
      selector:
        boolean: {}

    notify_on_start:
      name: Notify immediately on Home Assistant start if already in target state
      default: false
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input target_entity

  - platform: homeassistant
    event: start

variables:
  ent: !input target_entity
  desired: !input target_state
  tag: !input notification_tag
  notif_title: !input title
  channel: !input channel
  importance: !input importance
  sticky: !input make_sticky
  also_bad: !input show_when_unavailable
  notify_on_start: !input notify_on_start
  msg_in: !input message
  msg_default: >-
    {{ state_attr(ent, 'friendly_name') or ent }} is {{ states(ent) }}.
  msg: >-
    {{ (msg_in | trim) if (msg_in | trim) else msg_default }}

action:
  - choose:
      # SEND when in desired state (or optionally unavailable/unknown),
      # including on HA start (if enabled).
      - conditions:
          - condition: template
            value_template: >-
              {% set st = states(ent) %}
              {% if trigger.platform == 'homeassistant' and not notify_on_start %}
                false
              {% else %}
                (st == desired) or (also_bad and st in ['unavailable','unknown'])
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (channel | trim) != '' }}"
                sequence:
                  - service: !input notify_service
                    data:
                      title: "{{ notif_title }}"
                      message: "{{ msg }}"
                      data:
                        tag: "{{ tag }}"
                        persistent: "{{ sticky | bool }}"
                        channel: "{{ channel }}"
                        importance: "{{ importance }}"
            default:
              - service: !input notify_service
                data:
                  title: "{{ notif_title }}"
                  message: "{{ msg }}"
                  data:
                    tag: "{{ tag }}"
                    persistent: "{{ sticky | bool }}"
                    importance: "{{ importance }}"

    default:
      # CLEAR when not in desired state
      - service: !input notify_service
        data:
          message: clear_notification
          data:
            tag: "{{ tag }}"
