blueprint:
  name: Android sticky notification for entity state (auto-dismiss)
  description: >
    Sends a persistent (sticky) notification to an Android phone when an entity
    enters a target state, and clears it when the entity leaves that state.
    Requires Home Assistant Companion App on Android.
  domain: automation

  input:
    target_entity:
      name: Entity to monitor
      selector:
        entity: {}

    target_state:
      name: State that triggers the sticky notification
      description: 'Example: on, open, home, playing, locked'
      default: "on"
      selector:
        text: {}

    notify_service:
      name: Android notify service (exact)
      description: >
        Enter the exact service, e.g. notify.mobile_app_your_phone.
        Find it in Developer Tools → Services.
      selector:
        text: {}

    title:
      name: Notification title
      default: "Home Assistant"
      selector:
        text: {}

    message:
      name: Notification message (optional)
      default: ""
      selector:
        text:
          multiline: true

    notification_tag:
      name: Notification tag (used to update/clear)
      description: Must be unique per automation/phone (e.g. sticky_light_kitchen)
      default: "ha_sticky_state"
      selector:
        text: {}

    channel:
      name: Android notification channel (optional)
      default: ""
      selector:
        text: {}

    importance:
      name: Android importance (optional)
      default: "default"
      selector:
        select:
          options:
            - min
            - low
            - default
            - high
            - max

    make_sticky:
      name: Make notification sticky (persistent)
      default: true
      selector:
        boolean: {}

    show_when_unavailable:
      name: Also notify when entity is unavailable/unknown
      default: false
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input target_entity

variables:
  ent: !input target_entity
  desired: !input target_state
  notify_service: !input notify_service
  tag: !input notification_tag
  notif_title: !input title
  channel: !input channel
  importance: !input importance
  sticky: !input make_sticky
  also_bad: !input show_when_unavailable
  msg_in: !input message
  msg_default: >-
    {{ state_attr(ent, 'friendly_name') or ent }} is {{ states(ent) }}.
  msg: >-
    {{ (msg_in | trim) if (msg_in | trim) else msg_default }}

action:
  - choose:
      # SEND when entity enters desired state (or optionally unavailable/unknown)
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.to_state is not none and (
                   trigger.to_state.state == desired
                   or (also_bad and trigger.to_state.state in ['unavailable','unknown'])
                 ) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (channel | trim) != '' }}"
                sequence:
                  - service: !input notify_service
                    data:
                      title: "{{ notif_title }}"
                      message: "{{ msg }}"
                      data:
                        tag: "{{ tag }}"
                        persistent: "{{ sticky | bool }}"
                        channel: "{{ channel }}"
                        importance: "{{ importance }}"
            default:
              - service: !input notify_service
                data:
                  title: "{{ notif_title }}"
                  message: "{{ msg }}"
                  data:
                    tag: "{{ tag }}"
                    persistent: "{{ sticky | bool }}"
                    importance: "{{ importance }}"
    default:
      # CLEAR when entity leaves desired state
      - service: !input notify_service
        data:
          message: clear_notification
          data:
            tag: "{{ tag }}"
